### ISSUE TITLE
Make const_reference_proxy assignable to reference_proxy

### ISSUE THREAD

**Issue by JohanMabille** [man-group/sparrow#125]
`const_reference_proxy` should also be constructible from `reference_proxy`.

**Comment by DerThorsten** [comment]
@JohanMabille https://github.com/man-group/sparrow/pull/132

**Comment by DerThorsten** [comment]
@JohanMabille  do we need constructible  just assignable?

**Comment by DerThorsten** [comment]
> `const_reference_proxy` should also be constructible from `reference_proxy`.

do you mean the other way round or really this way?

**Comment by JohanMabille** [comment]
This is not needed anymore thanks to #135 and #136
