### ISSUE TITLE
Layout template parameter for the storage

### ISSUE THREAD

**Issue by JohanMabille** [man-group/sparrow#139]
The layout classes should have an additional template parameter for specifying the storage. Currently, they work with `array_data` only, which makes it complicated (if not impossible) to transfer data from [ArrowArray structures](https://arrow.apache.org/docs/dev/format/CDataInterface.html#structure-definitions).

The layout classe should be able to work with these structures. the [buffer_view](https://github.com/man-group/sparrow/blob/main/include/sparrow/buffer_view.hpp) and [dynamic_bitset_view](https://github.com/man-group/sparrow/blob/main/include/sparrow/dynamic_bitset.hpp#L166) classes can be built on top of the C strutures to ease their manipulation.

Free functions for retrieving the buffers / bitmap / children members should be added to avoid specializing the layout for each storage type (currently `array_data` and `ArrowArray`, but there might be others in the future).

**Comment by Klaim** [comment]
👍🏽 I think we can add a concept which matches either `array_data` or `ArrowArrray` , with requirements on operations which are the free functions (in sparrow namespace) and use that as the layout parameter. That way we double-check that we are doing this correctly.

**Comment by JohanMabille** [comment]
Thinking more about this, I think we should wrap ArrowArray in a structure to avoid rebuilding the buffer_views each time we need to access the data. These views would be allocated upon construction of the wrapper. In that cas, the data members should be private wth accessors. In that case, we could add accessors to the `array_data` class too and avoid the free functions.

**Comment by JohanMabille** [comment]
Actually the views are really cheap to build, so let's just build them in free access functions.
