### ISSUE TITLE
Provide an "array_view" class

### ISSUE THREAD

**Issue by JohanMabille** [man-group/sparrow#141]
When `typed_array` supports different storage types (see #140), an new `array_view` class should be provided. This class is meant to provide an array API to Arrow data provided by external libraries (via the [Arrow C data interface](https://arrow.apache.org/docs/dev/format/CDataInterface.html#structure-definitions)). Notice that this new class should provid a restricted API (only the const API of the array class), since we cannot manage the memory of the external structures.

This `array_view` will hold a variant of `typed_array` parmetrized by the ArrowArray storage, while the existing `array` class will remain unchanged.

**Comment by Klaim** [comment]
👍🏽 
There is a risk that the `array_view` name leads to misunderstanding, as it would not match "any arrow data storage" but only `ArrowArray`s. Also we want it to be reduced in capabilities and maybe the name needs to reflect that.

**Comment by Alex-PLACET** [comment]
`array_read_only` ?

**Comment by JohanMabille** [comment]
`external_array`?

**Comment by JohanMabille** [comment]
This class is not needed anymore now that the library has been refactored to handle imported arrays and arrays created with sparrow in a single class.
