### ISSUE TITLE
Implement metaprogramming utilities

### ISSUE THREAD

**Issue by JohanMabille** [man-group/sparrow#15]
This issue is too big to be implmeented in a single PR and has been split into smaller issues (the list will be updated while doing the work):

- [X] Metaprogramming basic tools: https://github.com/xtensor-stack/sparrow/issues/67
- [X] Support for half float type: https://github.com/xtensor-stack/sparrow/issues/68

The target architecture is something like:

```cpp
struct array_data
{
        data_descriptor type;
        std::int64_t length = 0;
        std::int64_t offset = 0;
        dynamic_bitset<std::uint8_t> bitmap;       // buffer 0 in C struct
        std::vector<buffer<std::uint8_t>> buffers; // buffer 1 to n in C struct 
        std::vector<array_data> child_data;
};

template <class T, class L = get_default_layout_t<T>>
class array_impl
{
    L m_layout;
    array_data m_data;
};

using array_variant = std::variant<
    array_impl<std::unint8_t>,
    array_impl<std::int8_t>,
    ...
    // all required types already supported in data_type.hpp
>;
```

We need to implement tools such as arrow_traits to retrieve the different associated types to a basic type:

```cpp
template <class T>
struct arrow_traits;

template <>
struct arrow_traits<std::unint8_t>
{
    using layout_type = primite_layout<std::uint8_t>;
};
```

It would be nice to use concepts / constraints to reduce the amount of code, and to be able to generate `array_impl` and other related types based on a typelist of supported types.

**Comment by JohanMabille** [comment]
This issue is too big to be implemented in a single PR; see below the list of smallest issues for implementing it (will be updated while doing the work):

- Metaprogramming basic tools: #67 
- Support for half float type: #68

**Comment by Klaim** [comment]
@JohanMabille Is there something missing or should we close this?

**Comment by JohanMabille** [comment]
We can close it.
