### ISSUE TITLE
Code factorization

### ISSUE THREAD

**Issue by JohanMabille** [man-group/sparrow#159]
The code of the `typed_array` [constructors](https://github.com/man-group/sparrow/blob/main/include/sparrow/array/typed_array.hpp#L334-L469) and the `array_data` factory [functions](https://github.com/man-group/sparrow/blob/main/include/sparrow/array/array_data_factory.hpp) is very similar, so it should be possible to refactor a bit so that constructors leverage the factory functions.

There are some constraints to adapt, and the signature of the factory functions should be changed to avoid extra copies: the bitmap argument should be passed by value, and moved in the resulting `array_data`.

**Comment by Klaim** [comment]
One of the other issues is that `typed_array` should never know how `array_data` is built, that should be knowledge coming from it's `layout_type`. Therefore, the `array_data` construction functions really need to be actually provided by the layouts. Then `typed_array` would just whatever is provided by it's `layout_type` to build an `array_data` from a range.

**Comment by DerThorsten** [comment]
This has been done via #164 and #169
