### ISSUE TITLE
Different endianness support

### ISSUE THREAD

**Issue by serge-sans-paille** [man-group/sparrow#176]
sparrow seems to make incorrect assumption on endianness, see `build.log` in https://koji.fedoraproject.org/koji/taskinfo?taskID=121660164

**Comment by serge-sans-paille** [comment]
On Tue, Aug 27, 2024 at 02:30:21AM -0700, Alexis Placet wrote:
> Hi ***@***.***
> We just merged a fix for the test and added CI jobs on big endian architectures
> (s390x included).

Thanks! Could that be worth a release?

**Comment by Alex-PLACET** [comment]
@serge-sans-paille Here it is: https://github.com/man-group/sparrow/releases/tag/0.0.4
