### ISSUE TITLE
Move tests from doctest to Catch2

### ISSUE THREAD

**Issue by Alex-PLACET** [man-group/sparrow#297]

**Comment by Gulin7** [comment]
Hi, @Alex-PLACET , I would like to work on this issue. Could you help with some background?

**Comment by Alex-PLACET** [comment]
Hi @Gulin7 
Welcome to the Sparrow project! We're excited to have you on board.
To get started, please take a look at our [README](https://github.com/man-group/sparrow/blob/main/README.md) and [DOCUMENTATION](https://man-group.github.io/sparrow/index.html). If you have any questions, feel free to ask directly in this issue/pull request.
We currently use Doctest, but as it's no more maintenanted, we decided to move to Catch2.
To start this transition we will not port all the tests, we will start with only one test file. The rest will be done in a second pull request.

- [ ] Modify the dependency requirements to add Catch2
  - [ ] VCPKG: https://github.com/man-group/sparrow/blob/main/vcpkg.json
  - [ ] Conda: https://github.com/man-group/sparrow/blob/main/environment-dev.yml
  - [ ] Conan: https://github.com/man-group/sparrow/blob/main/conanfile.py
- [ ] Modify CMake to use this Catch2 library
- [ ] Modify CMake and create a new target which use Catch2: https://github.com/man-group/sparrow/blob/main/test/CMakeLists.txt
- [ ] Modify `run_tests` and `run_tests_with_junit_report` targets to also run the new test target
- [ ] Port a single unit test file, like this one: https://github.com/man-group/sparrow/blob/main/test/test_allocator.cpp
- [ ] Modify the CI github action files to upload both test report files: https://github.com/man-group/sparrow/blob/main/.github/workflows/linux.yml#L98

I don't know if we will have to create a custom reporter like I did for DocTest. Let's discuss that in the PR.
https://github.com/catchorg/Catch2/blob/devel/docs/reporters.md
https://github.com/man-group/sparrow/blob/main/test/better_junit_reporter.hpp
https://github.com/man-group/sparrow/blob/main/test/junit_xml_writer.hpp

**Comment by Gulin7** [comment]
Hi, @Alex-PLACET , could we talk in private as I find it easier to communicate that way? Maybe you can add me on either discord: 250670176788283392 or linkedin: https://www.linkedin.com/in/gulin-tudor/ .
